version: '3.8'

services:
  app:
    build: 
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/db_postgres_fast
    volumes:
      - ./app:/app

  db:
    image: postgres
    environment:
      POSTGRES_DB: db_postgres_fast
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
